<a href="https://colab.research.google.com/github/fatihibnisa/my-ml-projekt/blob/main/murojatchilar_ustida_ishlar_va_data_bzazlar_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## murojat chilar ustiuda ishlash va data clear qilish va ularni postgeresqlga utkazish va oqitish

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_agentlik = pd.read_csv('agencies.csv')
df_murojat = pd.read_csv('appeals.csv')
df_fuqaro = pd.read_csv('citizens.csv')
df_hudud = pd.read_csv('regions.csv')
df_moliya_yor = pd.read_csv('subsidies.csv')
df_sorovlar = pd.read_csv('surveys.csv')

In [ ]:
df_agentlik.head()

   agency_id                                       agency_name
0          1                      Kommunal xizmatlar vazirligi
1          2                            Ichki ishlar vazirligi
2          3                                   Soliq qo‘mitasi
3          4  Bandlik va kambag‘allikni qisqartirish vazirligi
4          5                       Sog‘liqni saqlash vazirligi

In [ ]:
df_agentlik.shape

(15, 2)

In [ ]:
df_agentlik.isnull().sum()

agency_id      0
agency_name    0
dtype: int64

In [ ]:
df_agentlik.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   agency_id    15 non-null     int64
 1   agency_name  15 non-null     object
dtypes: int64(1), object(1)
memory usage: 372.0+ bytes

In [ ]:
df_murojat.head()

,appeal_id,citizen_id,region_id,agency_id,appeal_date,category,appeal_text,status,deadline_date,response_date
0,1,124,2,7,2025-08-28,Ijtimoiy yordam,Murojaat matni #1 mazkur masala yuzasidan yord...,Rejected,2025-09-09,2025-09-01
1,2,1029,8,6,2026-05-15,Bandlik,Murojaat matni #2 mazkur masala yuzasidan yord...,Rejected,2026-05-28,2026-06-15
2,3,3100,18,3,2026-03-19,Ijtimoiy yordam,Murojaat matni #3 mazkur masala yuzasidan yord...,Resolved,2026-04-06,2026-04-08
3,4,2919,6,6,2026-05-01,Transport,Murojaat matni #4 mazkur masala yuzasidan yord...,Resolved,2026-05-14,2026-05-29
4,5,2319,21,14,2025-05-12,Ijtimoiy yordam,Murojaat matni #5 mazkur masala yuzasidan yord...,Resolved,2025-06-09,2025-05-08

,appeal_id,citizen_id,region_id,agency_id,appeal_date,category,appeal_text,status,deadline_date,response_date
0,1,124,2,7,2025-08-28,Ijtimoiy yordam,Murojaat matni #1 mazkur masala yuzasidan yord...,Rejected,2025-09-09,2025-09-01
1,2,1029,8,6,2026-05-15,Bandlik,Murojaat matni #2 mazkur masala yuzasidan yord...,Rejected,2026-05-28,2026-06-15
2,3,3100,18,3,2026-03-19,Ijtimoiy yordam,Murojaat matni #3 mazkur masala yuzasidan yord...,Resolved,2026-04-06,2026-04-08
3,4,2919,6,6,2026-05-01,Transport,Murojaat matni #4 mazkur masala yuzasidan yord...,Resolved,2026-05-14,2026-05-29
4,5,2319,21,14,2025-05-12,Ijtimoiy yordam,Murojaat matni #5 mazkur masala yuzasidan yord...,Resolved,2025-06-09,2025-05-08

In [ ]:
df_murojat.shape

(10200, 10)

In [ ]:
df_murojat.columns

Index(['appeal_id', 'citizen_id', 'region_id', 'agency_id', 'appeal_date',
       'category', 'appeal_text', 'status', 'deadline_date', 'response_date'],
      dtype='object')

In [ ]:
df_murojat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   appeal_id      10200 non-null  int64
 1   citizen_id     10200 non-null  int64
 2   region_id      10200 non-null  int64
 3   agency_id      10200 non-null  int64
 4   appeal_date    10200 non-null  object
 5   category       10200 non-null  object
 6   appeal_text    10200 non-null  object
 7   status         10200 non-null  object
 8   deadline_date  10200 non-null  object
 9   response_date  6790 non-null   object
dtypes: int64(4), object(6)
memory usage: 797.0+ KB

In [ ]:
df_murojat.isnull().sum()

appeal_id           0
citizen_id          0
region_id           0
agency_id           0
appeal_date         0
category            0
appeal_text         0
status              0
deadline_date       0
response_date    3410
dtype: int64

In [ ]:
df_fuqaro.head()

   citizen_id        full_name  birth_year gender  region_id
0           1    Bobur Karimov        1961   Ayol          8
1           2  Malika Tursunov        1966  Erkak         19
2           3    Sardor Isayev        1961  Erkak          7
3           4   Malika Yusupov        1998  Erkak         18
4           5   Malika Yusupov        1986  Erkak         15

In [ ]:
df_fuqaro.shape

(5000, 5)

In [ ]:
df_fuqaro.isnull().sum()

citizen_id    0
full_name     0
birth_year    0
gender        0
region_id     0
dtype: int64

In [ ]:
df_fuqaro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   citizen_id  5000 non-null   int64
 1   full_name   5000 non-null   object
 2   birth_year  5000 non-null   int64
 3   gender      5000 non-null   object
 4   region_id   5000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 195.4+ KB

In [ ]:
df_fuqaro['birth_year'] = pd.to_datetime(df_fuqaro['birth_year'])

In [ ]:
df_fuqaro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   citizen_id  5000 non-null   int64
 1   full_name   5000 non-null   object
 2   birth_year  5000 non-null   datetime64[ns]
 3   gender      5000 non-null   object
 4   region_id   5000 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 195.4+ KB

In [ ]:
df_hudud.head()

   region_id        region_name  district_id  district_name
0          1    Toshkent shahri           10      Yunusobod
1          2    Toshkent shahri           20      Chilonzor
2          3    Toshkent shahri           30  Mirzo Ulugbek
3          4  Toshkent viloyati           40         Chinoz
4          5  Toshkent viloyati           50       Zangiota

In [ ]:
df_hudud.isnull().sum()

region_id        0
region_name      0
district_id      0
district_name    0
dtype: int64

In [ ]:
df

   subsidy_id  appeal_id  amount_allocated            subsidy_type
0           1       3463         917319.83        Imtiyozli kredit
1           2       5013       13669790.71  Dehqonchilik uchun yer
2           3       4154        4602397.41           Moddiy yordam
3           4       5172        4123307.17        Imtiyozli kredit
4           5        632       10787272.98        Bepul davolanish